# Generated by Django 3.0.5 on 2021-03-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='resume',
            field=models.FileField(default='None', upload_to='resume'),
            preserve_default=False,
        ),
    ]
